feature: add support for user supplied shacl as file
Informasjonsforvaltning/dcat-ap-no-validator-service pull request #34
Opened 2021-01-29 13:59 UTC by stigbd

closes #31

2021-02-08 12:24 UTC, azaxarov requested changes

2021-02-08 12:24 UTC, azaxarov commented on README.md
> + -F "shacl-file=@dcat-ap-no-shacl_shapes_2.00.ttl" \
Hvordan fungerer kombinasjon av shacl-file og config.shapeId?

2021-02-08 12:24 UTC, azaxarov commented on src/dcat_ap_no_validator_service/view/validator.py
> +                graph=data, shacl=shacl, format=content_type, config=config
Jena bruker "shapes" framfor "shacl", så det kan være greit å holde oss til konvensjonen

2021-02-08 12:24 UTC, azaxarov commented on src/dcat_ap_no_validator_service/view/validator.py
> +                logging.debug(f"content of {filename}:\n{data}")
Ser ikke ut som data er definert for denne if-setningen

2021-02-08 12:24 UTC, azaxarov commented on src/dcat_ap_no_validator_service/view/validator.py
> +                    logging.debug(f"content_type of {content_type}")
```suggestion
                logging.debug(f"Got SHACL shapes from user with filename: {part.filename} and contents of type: {part.headers[hdrs.CONTENT_TYPE]}")

```

2021-02-08 12:24 UTC, azaxarov commented on src/dcat_ap_no_validator_service/view/validator.py
> +                logging.debug(f"content of {filename}:\n{data}")
```suggestion
                logging.debug(f"content of {part.filename}:\n{data}")

```

2021-02-08 12:24 UTC, azaxarov commented on src/dcat_ap_no_validator_service/service/validator_service.py
> +                self.ograph += g
```suggestion
                self.ograph += fetch_graph(o)
```

2021-02-08 12:24 UTC, azaxarov commented on src/dcat_ap_no_validator_service/service/validator_service.py
> +                        self.ograph += g
```suggestion
                        self.ograph += fetch_graph(o)
```

2021-02-08 12:24 UTC, azaxarov commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +    resp = requests.get(url, headers=headers)
```suggestion
    resp = requests.get(url, headers={"Accept": "text/turtle"})
```

2021-02-08 12:24 UTC, azaxarov commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +        format = resp.headers["content-type"].split(";")[0]
```suggestion
        format = resp.headers[hdrs.CONTENT_TYPE].split(";")[0]
```

2021-02-08 12:24 UTC, azaxarov commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +        format = resp.headers["content-type"].split(";")[0]
Unødvendig å definere format her, synes jeg. text/turtle er uansett første format som blir forsøkt parset

2021-02-08 12:24 UTC, azaxarov commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +def parse_text(input_graph: Any, format: Any = None) -> Graph:
```suggestion
def parse_text(input_graph: str) -> Graph:
```

2021-02-08 12:24 UTC, azaxarov commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +    else:
Ta bort if-else

2021-02-09 10:18 UTC, jeffreiffers requested changes

2021-02-09 10:18 UTC, jeffreiffers commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +    resp = requests.get(url, headers=headers)
Bruk hdrs,ACCEPT

2021-02-09 10:18 UTC, jeffreiffers commented on src/dcat_ap_no_validator_service/service/validator_service.py
> +                        logging.debug(f"Trying to fetch remote triples about {o}")
Skal man alltid logge debug? Man bør sjekke om logging konfig har debug på. Man sparer både resurser og mengde med logging.

2021-02-12 11:42 UTC, stigbd commented on src/dcat_ap_no_validator_service/view/validator.py
> +                graph=data, shacl=shacl, format=content_type, config=config
Godt spotta. Har refaktorert alle "ekstern" variable i b86c70502db44ebfa788ccaec3439870d58b661d. Skal fikse resten i seinare kommits.

2021-02-12 11:49 UTC, jeffreiffers requested changes

2021-02-12 11:49 UTC, jeffreiffers commented on src/dcat_ap_no_validator_service/view/validator.py
> +            if part.name == "data-graph-url":
Bruk gjerne enum fremfor string. Gjelder alle parter!

2021-02-13 13:36 UTC, stigbd commented on src/dcat_ap_no_validator_service/view/validator.py
> +                graph=data, shacl=shacl, format=content_type, config=config
Skal vere fiksa i 575005baa6e3e6d6845f97ae01afdd152a969da4

2021-02-13 13:36 UTC, stigbd commented on src/dcat_ap_no_validator_service/view/validator.py
> +                    logging.debug(f"content_type of {content_type}")
Fiksa i 575005baa6e3e6d6845f97ae01afdd152a969da4

2021-02-13 13:37 UTC, stigbd commented on src/dcat_ap_no_validator_service/view/validator.py
> +                logging.debug(f"content of {filename}:\n{data}")
Fjerna bruk av lokal variabel `filename`. Fiksa i 575005baa6e3e6d6845f97ae01afdd152a969da4

2021-02-13 13:37 UTC, stigbd commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +    resp = requests.get(url, headers=headers)
Fiksa i 575005baa6e3e6d6845f97ae01afdd152a969da4

2021-02-13 13:37 UTC, stigbd commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +        format = resp.headers["content-type"].split(";")[0]
Fiksa i 575005baa6e3e6d6845f97ae01afdd152a969da4

2021-02-13 13:38 UTC, stigbd commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +        format = resp.headers["content-type"].split(";")[0]
`format` er fjerna. Ref 575005baa6e3e6d6845f97ae01afdd152a969da4

2021-02-13 13:38 UTC, stigbd commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +def parse_text(input_graph: Any, format: Any = None) -> Graph:
Fiksa i 575005baa6e3e6d6845f97ae01afdd152a969da4

2021-02-13 13:38 UTC, stigbd commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +    else:
Utført i 575005baa6e3e6d6845f97ae01afdd152a969da4

2021-02-13 13:40 UTC, stigbd commented on src/dcat_ap_no_validator_service/view/validator.py
> +            if part.name == "data-graph-url":
Utført i 575005baa6e3e6d6845f97ae01afdd152a969da4

2021-02-13 13:45 UTC, stigbd commented on README.md
> + -F "shacl-file=@dcat-ap-no-shacl_shapes_2.00.ttl" \
Dersom shacl-file (no: shapes-graph-file) er gitt input, overstyrer den config, også om denne er gitt av bruker i config.shapesId.

Mulig dette burde dokumenteres bedre, evt kaste en excpetion (gi brukerfeil) dersom begge er gitt i input.

2021-02-13 13:46 UTC, stigbd commented on src/dcat_ap_no_validator_service/service/validator_service.py
> +                        logging.debug(f"Trying to fetch remote triples about {o}")
Logging er satt default til INFO:
```
load_dotenv()
LOGGING_LEVEL = os.getenv("LOGGING_LEVEL", "INFO")
...
    # logging configurataion:
    logging.basicConfig(
        format="%(asctime)s,%(msecs)d %(levelname)s - %(module)s:%(lineno)d: %(message)s",
        datefmt="%H:%M:%S",
        level=LOGGING_LEVEL,
    )
```

2021-02-15 10:08 UTC, azaxarov approved these changes

2021-02-15 10:08 UTC, azaxarov commented on src/dcat_ap_no_validator_service/service/validator_service.py
> +            self.data = parse_text(data)
```suggestion
        self.data = fetch_graph(url) if self.url or parse_text(data)
```

2021-02-15 10:20 UTC, stigbd commented on README.md
> +  "shapesId": "2",
Ja, for etter kvart blir det mulig å liste opp alle shapes grapher backend støtter (som blir utvida etter kvart med feks skos-ap-no, modelldcat-ap-no..)

2021-02-15 10:30 UTC, stigbd commented on src/dcat_ap_no_validator_service/service/validator_service.py
> +            self.data = parse_text(data)
Hehehe, forslaget gav meg bad syntax. Tenker du meiner:
```
self.data = fetch_graph(url) if self.url else parse_text(data)
```

2021-02-15 10:38 UTC, stigbd commented on src/dcat_ap_no_validator_service/adapter/remote_graph_adapter.py
> +SUPPORTED_FORMATS = set(["text/turtle", "application/ld+json", "application/rdf+xml"])
Har sjekka. Det er dessverre ikkje støtte for dette, så langt eg kan sjå.

2021-02-15 13:15 UTC, jeffreiffers commented on README.md
> +  "shapesId": "2",
Kan vi ikke slå sammen shapes-graph-file og shapeId? Synes det blir uryddig, hvor man skal bruke hva. Hva med hvis vi legger til shapes-graph-url og backend laster ned shapes filen. 

Noen oppsjoner hvordan klienten kan kalle valideringen:

1. shapes-graph-url: 'dcat-ap-no-shacl_shapes_2.00.ttl'
2. shapes-graph-url: 'https://validator.staging.fellesdatakatalog.digdir.no/shapes/dcat-ap-no-shacl_shapes_2.00.ttl'
3. shapes-graph-url: 'https://myshape.ttl'

Slik holder vi grensesnittet ryddig.

2021-02-15 13:31 UTC, jeffreiffers commented on dcat-ap-no-validator-service.yaml
> +        shapesId:
Flytte til input part

2021-02-15 13:31 UTC, jeffreiffers commented on src/dcat_ap_no_validator_service/service/validator_service.py
> +    shapes_id: str = DEFAULT_SHAPE_GRAPH
```suggestion
    shapes_id: str = DEFAULT_SHAPES_GRAPH
```

2021-02-15 13:31 UTC, jeffreiffers commented on src/dcat_ap_no_validator_service/service/validator_service.py
> +                        logging.debug(f"Trying to fetch remote triples about {o}")
Det jeg mente var egentlig noe som dette 

```
if logger.isEnabledFor(logging.DEBUG):
    logging.debug("Message with %s, %s", expensive_func1(), expensive_func2())
```
                                       
Man sparer cpu ved å ikke kalle logging.debug. Enklest er å lage en wrapper metode som erstatter logging.debug().

2021-02-15 13:43 UTC, azaxarov commented on README.md
> +  "shapesId": "2",
Jeg støtter forslaget til Jeff. `shapesId` kan erstattes med nye parametre `shapes-graph-url`. Det holder kanskje med et unikt URI på shapes, noe som kan senere eksponeres ut via et endepunkt.

Hvis vi definerer våre shapes grafer i slik format:
- https://validator.staging.fellesdatakatalog.digdir.no/shapes/dcat-ap-no-1.1
- https://validator.staging.fellesdatakatalog.digdir.no/shapes/dcat-ap-no-2.0
- https://validator.staging.fellesdatakatalog.digdir.no/shapes/<unik shape ID>

så kan backend mappe disse URIene til interne filreferanser som allerede finnes.

2021-02-15 14:12 UTC, stigbd commented on src/dcat_ap_no_validator_service/service/validator_service.py
> +                        logging.debug(f"Trying to fetch remote triples about {o}")
Har tatt denne ut i eget issue #39

2021-02-15 14:33 UTC, stigbd commented on README.md
> +  "shapesId": "2",
Enig. Har oppretta issue #40 . Antagelegvis implementerer vi denne sammen med #9

2021-02-15 15:06 UTC, stigbd commented on dcat-ap-no-validator-service.yaml
> +        shapesId:
Denne forstod eg ikkje. Tenker at vi rydder opp i dette når vi løyser #40

2021-02-17 10:00 UTC, jeffreiffers approved these changes

2021-02-17 10:15 UTC, merged